package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"
	"example/internal/gql/model"
)

// Links is the resolver for the links field.
func (r *queryResolver) Links(ctx context.Context) ([]*model.Link, error) {
	// var links []*model.Link
	// dummyLink := model.Link{
	// 	Title:   "our dummy link",
	// 	Address: "https://address.org",
	// 	User:    &model.User{Name: "admin"},
	// }
	// links = append(links, &dummyLink)
	// return links, nil
	var resultLinks []*model.Link
	var dbLinks []model.Link
	var nilLink *model.Link
	dbLinks = nilLink.GetAll()
	for _, link := range dbLinks {
		resultLinks = append(resultLinks, &model.Link{ID: link.ID, Title: link.Title, Address: link.Address})
	}
	return resultLinks, nil
}
